package Pojos;
// Generated Nov 1, 2018 12:38:46 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Antrian generated by hbm2java
 */
public class Antrian  implements java.io.Serializable {


     private String namaRs;
     private String namaPsn;
     private String alamatPsn;
     private Date date;

    public Antrian() {
    }

    public Antrian(String namaRs, String namaPsn, String alamatPsn, Date date) {
       this.namaRs = namaRs;
       this.namaPsn = namaPsn;
       this.alamatPsn = alamatPsn;
       this.date = date;
    }
   
    public String getNamaRs() {
        return this.namaRs;
    }
    
    public void setNamaRs(String namaRs) {
        this.namaRs = namaRs;
    }
    public String getNamaPsn() {
        return this.namaPsn;
    }
    
    public void setNamaPsn(String namaPsn) {
        this.namaPsn = namaPsn;
    }
    public String getAlamatPsn() {
        return this.alamatPsn;
    }
    
    public void setAlamatPsn(String alamatPsn) {
        this.alamatPsn = alamatPsn;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


