package Pojos;
// Generated Nov 1, 2018 12:38:46 PM by Hibernate Tools 4.3.1



/**
 * RumahSakit generated by hbm2java
 */
public class RumahSakit  implements java.io.Serializable {


     private String userNameRs;
     private String passwordRs;
     private String namaRs;
     private String alamatRs;
     private int telpRs;
     private String emailRs;
     private int limitAntriRs;

    public RumahSakit() {
    }

    public RumahSakit(String userNameRs, String passwordRs, String namaRs, String alamatRs, int telpRs, String emailRs, int limitAntriRs) {
       this.userNameRs = userNameRs;
       this.passwordRs = passwordRs;
       this.namaRs = namaRs;
       this.alamatRs = alamatRs;
       this.telpRs = telpRs;
       this.emailRs = emailRs;
       this.limitAntriRs = limitAntriRs;
    }
   
    public String getUserNameRs() {
        return this.userNameRs;
    }
    
    public void setUserNameRs(String userNameRs) {
        this.userNameRs = userNameRs;
    }
    public String getPasswordRs() {
        return this.passwordRs;
    }
    
    public void setPasswordRs(String passwordRs) {
        this.passwordRs = passwordRs;
    }
    public String getNamaRs() {
        return this.namaRs;
    }
    
    public void setNamaRs(String namaRs) {
        this.namaRs = namaRs;
    }
    public String getAlamatRs() {
        return this.alamatRs;
    }
    
    public void setAlamatRs(String alamatRs) {
        this.alamatRs = alamatRs;
    }
    public int getTelpRs() {
        return this.telpRs;
    }
    
    public void setTelpRs(int telpRs) {
        this.telpRs = telpRs;
    }
    public String getEmailRs() {
        return this.emailRs;
    }
    
    public void setEmailRs(String emailRs) {
        this.emailRs = emailRs;
    }
    public int getLimitAntriRs() {
        return this.limitAntriRs;
    }
    
    public void setLimitAntriRs(int limitAntriRs) {
        this.limitAntriRs = limitAntriRs;
    }

    public String toJson() {
        return "(\"userNameRs\":" + getUserNameRs()+ "\"passwordRs\":" 
                + getPasswordRs() + "\"namaRs\":" + getNamaRs() + "\"alamatRs\":" 
                + getAlamatRs() + "\"telpRs\":" + getTelpRs() + "\"emailRs\":" 
                + getEmailRs() + "\"limitAntriRs\":" + getLimitAntriRs() + ")";
    }


}


